### ISSUE TITLE
Global MatDialog not showing up in other pages

### ISSUE THREAD

**Issue by imtrobin** [SamProf/MatBlazor#583] opened 2020-05-28 14:13 UTC
Hi, I'm trying to make a global MatDialog that I can call from static function, and I keep a static instance around.

It works when the MatDialog is called from the same page, but it doesn't show when it's called from another page.

e.g
in Index.razor

```
// This works fine
<MatButton OnClick='(e => ShowMessageBoxModal("test","test"))'>Test</MatButton>

<MatDialog @ref="MessageBoxModalInstance" CanBeClosed="false" @bind-IsOpen="@IsMessageBoxModalVisible">
    <MatDialogTitle>@MessageBoxModalTitle</MatDialogTitle>
    <MatDialogContent>
        @MessageBoxModalMessage
    </MatDialogContent>
    <MatDialogActions>
        <MatButton OnClick="@HideMessageBoxModal">OK</MatButton>
    </MatDialogActions>
</MatDialog>
@code
{
    static MatDialog   MessageBoxModalInstance     = default!;
    static string          MessageBoxModalMessage      = default!;
    static string          MessageBoxModalTitle        = default!;
    static bool            IsMessageBoxModalVisible    = false;

    void  HideMessageBoxModal () => IsMessageBoxModalVisible = false;

    public static void   ShowMessageBoxModal (string title, string message)
    {
        MessageBoxModalTitle = title;
        MessageBoxModalMessage = message;

        //MessageBoxModalInstance.Show ();
        IsMessageBoxModalVisible = true;
    }
}

In  AnotherPage.razor, nothing shows
<MatButton OnClick='(e => Index.ShowMessageBoxModal("test","test"))'>Test</MatButton>
```

Fiddle is [here](https://blazorfiddle.com/s/sh7lx7t3) but I couldn't get the navigate to anotherpage to see the error

**Comment by RonPeters** [comment] 2020-05-28 19:20
There is no such thing as a static global in the stateless nature of HTTP. However, you can reuse your code by moving the dialog/modal code into a Blazor component and including that component on the individual pages or in the main layout.

Closing as not a bug.

**Closed by RonPeters** 2020-05-28 19:20 UTC
Labels: bug

**Comment by imtrobin** [comment] 2020-05-29 00:48
You are closing this without reading it carefully. The issue is not about stateless HTTP.

I already have the Dialog as a Blazor component and I have placed it in MainLayout page.  I used the same pattern on another blazor framwork I'm tesitng, and their dialog shows up fine across pages.

**Comment by imtrobin** [comment] 2020-05-29 01:22
Anyway I solved it, it needs StateHasChanged

**Comment by RonPeters** [comment] 2020-05-29 04:14
@imtrobin I did read your issue carefully and I knew that static global was a red herring. The stateless nature of HTTP drives the design of frameworks such as Blazor and how they operate and hold onto, even though it seems like a non sequitur. What I could have asked was whether you were using server-based or wasm, which could make a difference.

In any case, I'm glad you were able to identify the real issue.

**Comment by imtrobin** [comment] 2020-05-30 03:00
You can close this now, thanks
