### ISSUE TITLE
MatTextField FullWidth=true with Icon; Icon and input overlap.

### ISSUE THREAD

**Issue by groogiam** [SamProf/MatBlazor#276] opened 2019-10-02 04:04 UTC
The input appears to overlap with a leading icon when FullWidth is true.

```html
<MatTextField @bind-value="@MyString8" Label="Trailing Icon - Password" Icon="lock_outline" IconTrailing="true" FullWidth="true" Required="true" Type="password"></MatTextField>
````
![image](https://user-images.githubusercontent.com/1992395/66017212-dd996600-e4a7-11e9-8833-b345a5ab2786.png)

**Comment by EduVencovsky** [comment] 2020-03-23 16:47
The problem is here

    padding: 20px 16px 6px;

![image](https://user-images.githubusercontent.com/37600269/77340847-a09e8580-6d0c-11ea-8537-2ebdca8368d5.png)

For other inputs, this padding if fine, but when it have an icon, it should be 

    padding: 20px 16px 6px 48px;

![image](https://user-images.githubusercontent.com/37600269/77340920-bc099080-6d0c-11ea-8f32-929876b3659e.png)

I think this is easy to fix, if someone can do a pull request, that would be nice.

**Comment by groogiam** [comment] 2020-04-04 01:42
@EduVencovsky I'm not seeing a matBlazor.css file that is not minified. Am I missing this file or are edits being made to the minified version in the dist folder directly?

**Comment by EduVencovsky** [comment] 2020-04-04 02:14
@groogiam sorry, I don't understand what you mean and what you want to know. You want to find where to edit the css?

**Comment by groogiam** [comment] 2020-04-04 02:20
@EduVencovsky The css file is minified. Everything is squashed into a single line making it very hard to edit. Typically this is run as a post processing step and the repository code has a file which has proper indentation and spacing. I was just wondering if I was missing that file. But it appears the minified file in src/MatBlazor/wwwroot/dist/matBlazor.css is being edited in the minified form.

**Comment by groogiam** [comment] 2020-04-04 02:22
@EduVencovsky The fix you have suggested works but there is an issue that the text is indented if the icon is marked as trailing. The css does not seem to take into account the location of icon.

<MatTextField @bind-Value="@myStringValue" Label="Standard" Icon="lock_outline" IconTrailing="true" FullWidth="true"></MatTextField>

![image](https://user-images.githubusercontent.com/1992395/78416697-b6f3ed80-75f8-11ea-8da3-b538df0a62ce.png)

**Comment by EduVencovsky** [comment] 2020-04-04 02:24
@groogiam I have edited in the browser just to see what is need to make it work, but haven't had time to look at the project to actually perform any change to the code.

**Comment by EduVencovsky** [comment] 2020-04-04 02:32
I just fixed you problem with #483 

Someone just forgot to add an `!important` to the correct padding of the `leading icon`

**Comment by groogiam** [comment] 2020-04-04 03:28
@EduVencovsky Excellent! Thanks for your help.

**Comment by EduVencovsky** [comment] 2020-04-30 12:12
This issue can be closed as the pull request already got merged and soon will be released

**Comment by lindespang** [comment] 2020-04-30 13:52
@EduVencovsky Thanks, nice work!

**Closed by lindespang** 2020-04-30 13:52 UTC
