### ISSUE TITLE
MatTable sample code - expected exception (There is no registered service of type 'System.Net.Http.HttpClient'), but what is the solution?

### ISSUE THREAD

**Issue by wvmstr** [SamProf/MatBlazor#655] opened 2020-07-23 09:44 UTC
I am attempting to use the sample paginator code for MatTable (WASM).

This piece of code won't run and results in There is no registered service of type 'System.Net.Http.HttpClient'

I found all the threads on this exception, dating back almost 12 months.

Except for "MatTable expects a HttpClient" I have not seen the exact way of doing that. 

Please advise what @usings or @injects I need to make this work?

`<MatTable Items="@cars" class="mat-elevation-z5">
            <MatTableHeader>
                <th>Name</th>
                <th>Price</th>
                <th>Horsepower</th>
            </MatTableHeader>
            <MatTableRow>
                <td>@context.Name</td>
                <td>@String.Format("${0:f2}", @context.Price)</td>
                <td>@context.Horsepower</td>
            </MatTableRow>
        </MatTable>
 
        @code
        {
 
            public class Car
            {
                public string Name { get; set; }
                public double Price { get; set; }
                public int Horsepower { get; set; }
 
                public Car(string name, double price, int horsepower)
                {
                    Name = name;
                    Price = price;
                    Horsepower = horsepower;
                }
            }
 
            Car[] cars = new[]
            {
                new Car("Volkswagen Golf", 10000, 220),
                new Car("Volkswagen Passat", 11000, 240),
                new Car("Volkswagen Polo", 12000, 110),
                new Car("Ford Focus", 13000, 200),
                new Car("Ford Fiesta", 14000, 160),
                new Car("Ford Fusion", 15000, 260),
                new Car("Ford Mondeo", 16000, 120),
            };
 
        }`

**Comment by lindespang** [comment] 2020-07-24 19:47
@wvmstr Hello!

The MatTable has an @inject attribute and is trying to inject a HttpClient from the DI container. The error you get means that the container could not provide an HttpClient to inject and fails.

To make this work: Register how you want HttpClient's to be resolved in your Program.cs. Check out docs on microsoft: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1

However, I personally don't like that there such dependencies in the framework - but that's another discussion I guess (Have not personally used the table)

**Comment by wvmstr** [comment] 2020-07-24 21:20
@lindespang Hey!

The page now looks like this, still get the same error message

`@page "/matpage"
@using System.Net.Http
@inject HttpClient Http 


<h3>MatPage</h3>

<MatTable Items="@cars" class="mat-elevation-z5">
    <MatTableHeader>
        <th>Name</th>
        <th>Price</th>
        <th>Horsepower</th>
    </MatTableHeader>
    <MatTableRow>
        <td>@context.Name</td>
        <td>@String.Format("${0:f2}", @context.Price)</td>
        <td>@context.Horsepower</td>
    </MatTableRow>
</MatTable>`

**Comment by lindespang** [comment] 2020-07-24 22:08
@wvmstr What you are doing now is simply trying to inject the HttpClient again, but the problem is that no http client is **registered** in the container. When you are injecting stuff you can only inject things that are **registered**

Try this in your Program.cs (assuming you are trying to call an api on your host)
```
builder.Services.AddScoped(sp => 
    new HttpClient
    {
        BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
    });
```

**Comment by wvmstr** [comment] 2020-07-25 01:55
Ahhh...... I see.

Got myself into a hole.
My Program.cs has this:
`builder.Services.AddHttpClient("ServerAPI", client =>
            {
                client.BaseAddress = new Uri(@"https://localhost:44393/");
                client.DefaultRequestHeaders.Add("Accept", "application/json");
            });`

In my razor page:
`@inject IHttpClientFactory ClientFactory`

and

`var httpClient = ClientFactory.CreateClient("ServerAPI");
 usernames = await httpClient.GetFromJsonAsync<UserName[]>("api/usernames");`

Thanks for clearing that up for me!

**Comment by lindespang** [comment] 2020-07-25 09:36
@wvmstr No problems great you solved it!

**Closed by lindespang** 2020-07-25 09:36 UTC
Labels: question
