### ISSUE TITLE
MatSelectItem cannot change selected value in code

### ISSUE THREAD

**Issue by doyce** [SamProf/MatBlazor#524] opened 2020-05-04 16:13 UTC
I have a MatSelectItem element bound to a collection of items and to a selected value property. When the bound collection is changed (different items are loaded based on user interaction) and I want to change the selected value in code by assigning a value to the bound property, an error pops up in the browser console (see bellow) and the MatSelectItem's selected value becomes blank. Note that the error occurs only with attempt to select value other than the first value in the bound collection.

```
Uncaught (in promise) Error: System.FormatException: Input string was not in a correct format.
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x28d9128 + 0x000ce> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo& callInfo, Microsoft.JSInterop.Infrastructure.IDotNetObjectReference objectReference, System.String argsJson) <0x353fef0 + 0x0017a> in <filename unknown>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, System.String argsJson) <0x353f3a0 + 0x0009e> in <filename unknown>:0 
    at Object.endInvokeDotNetFromJS (https://localhost:5003/_framework/blazor.webassembly.js:1:10117)
    at Object.invokeJSFromDotNet (https://localhost:5003/_framework/blazor.webassembly.js:1:9737)
    at _mono_wasm_invoke_js_marshalled (https://localhost:5003/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171485)
    at do_icall (wasm-function[6049]:0x111976)
    at do_icall_wrapper (wasm-function[1896]:0x52c3e)
    at interp_exec_method (wasm-function[1120]:0x25a03)
    at interp_runtime_invoke (wasm-function[5654]:0xf944e)
    at mono_jit_runtime_invoke (wasm-function[5108]:0xdfbfa)
    at do_runtime_invoke (wasm-function[1410]:0x3db59)
    at mono_runtime_try_invoke (wasm-function[418]:0xcfd4)
```

I'm using MatBlazor version 2.4.3 and Blazor version 3.2.0-preview5

**Comment by lindespang** [comment] 2020-05-05 17:14
Hi!

Thanks for using MatBlazor.
Could you try to reproduce this error in a Blazorfiddle using a mock example of your code? Thanks

https://blazorfiddle.com/ Hit save and share resulting link

**Comment by americanslon** [comment] 2020-05-06 15:56
Not them but I have the same error so here is the fiddle.  https://blazorfiddle.com/s/85817s4v

The fiddle is an almost exact approximation of what I am doing adjusted to use placeholder api
What's interesting is once I finished building the fiddle ...it worked. Only in the fiddle though.
Firmly believing I am insane I then took the EXACT fiddle code and stuck in in my application and boom error again. I then tried to move the code around to avoid the potential complicating factors of the remainder of the application and I still get the error. I now have it on a plain page at the top level of the app with nothing but the fiddle code and still get the error. 

Perhaps someone can try this exact code in a fresh app to see what they get.

MatBlazor version 2.3.0 and Blazor version 3.2.0-preview5. 
It seems blazorfiddle is using an older blazor preview. Maybe try updating the blazorfiddle's guts to compare apples to apples?

**Comment by doyce** [comment] 2020-05-06 19:02
I managed to reproduce the error partially using BlazorFiddle. In the fiddle, the error message appears in console but the value in MatSelectItem is changed. When I run the same code on my local machine using Visual Studio, the selected value is not changed though.

https://blazorfiddle.com/s/u8fjxxbg

I discovered that the bug appears also when setting the first item in the collection when it is first initialized as empty. I was initializing it with a list containing a single item as a workaround when I run into this bug earlier but didn't realized it's extent then, I just needed to select the first item after the list was loaded.

**Comment by lindespang** [comment] 2020-05-07 11:16
Thanks for the examples guys!

**Comment by lindespang** [comment] 2020-05-07 21:32
I've identified the issue and will post a fix in the near future.

**Comment by lindespang** [comment] 2020-05-08 23:34
Seems as there was a problem with the MDC select Component that was recently fixed https://github.com/material-components/material-components-web/pull/5870

Unfortunately it just missed the 6.0.0 release.

I think this will solve the issue and don't think I want to do a hack in MatBlazor until I can see how this fix turns out.

Closing this as a duplicate please follow #494 for further updates.

**Closed by lindespang** 2020-05-08 23:34 UTC
Labels: bug
