### ISSUE TITLE
Text field label color

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#513] opened 2020-04-27 14:12 UTC
Hi! 
Great work so far!

I noticed that despite using a theme provider, the label of the outlined input field is still displayed is purple.

<img width="411" alt="Képernyőfotó 2020-04-27 - 16 10 45" src="https://user-images.githubusercontent.com/43353335/80381985-02b95000-88a2-11ea-9d01-ab57b3ba14f4.png">

Is there a way to change it?

Thanks.

**Comment by EduVencovsky** [comment] 2020-04-27 14:42
Duplicate of #419 and #488 fix this

**Closed** 2020-04-27 15:09 UTC
