### ISSUE TITLE
MatSelect "Cannot read property 'classList' of undefined" when selected value does not exist in list after Bound List updates

### ISSUE THREAD

**Issue by dorana** [SamProf/MatBlazor#780] opened 2020-11-09 12:06 UTC
**Describe the bug**
Null reference (cannot read property 'classList' of undefined)
Error happens when you have a MatSelect that is bind to a list that is updated based on external means (other selects, fetch etc) when the previous selected value does not exist in the new list.

This happens even if the bound value is set to null before updating the list itself

When creating the Example in BlazorFiddle it works as expected.
Copying this exact code to my Blazor Project (Blazor Server) it creates the error

**To Reproduce**
Create 2 lists somewhat like the example below
```
var listA = new List<string> //this will be a list of types
var listB = new List<Example>
```

create 2 MatSelects
Bind Select A to ListA
Bind Select B to a filtered list of A (ListB.Where(x => x.Type == SelectedValueFromSelectA)

Select a value i list A to populate list B
Select a value in Select a value in Select B
Select a value in List A that does NOT have the already selected option in Select B

**Blazorfiddle link**
https://blazorfiddle.com/s/wmxrt6qk

**Expected behavior**
Select B should clear and only display available options
As it shows in BlazorFiddler

**Screenshots**
If applicable, add screenshots or .GIF captures to help explain your problem.
![image](https://user-images.githubusercontent.com/72192219/98538592-464a3900-228b-11eb-9406-2da3e41fd638.png)

**Additional context**
Workaround done by compiling js from Github and using this JS file instead of the one bundles in the NuGet,
trhen adding null check
```
removeClassAtIndex: function (e, n) {
    if (t.menu.items[e] != null && t.menu.items[e].classList != null) {
        t.menu.items[e].classList.remove(n);
    }
}
```

**Comment by naretto** [comment] 2020-11-15 23:15
Isn't this a duplicate of https://github.com/SamProf/MatBlazor/issues/651?

**Comment by dorana** [comment] 2020-11-15 23:29
> Isn't this a duplicate of #651?

Yes it is. I will transfer workaround and close this issue

**Closed** 2020-11-15 23:35 UTC
Labels: bug
