### ISSUE TITLE
Exception on Blazor Server for MatTable because no HttpClient service registered

### ISSUE THREAD

**Issue by whentotrade** [SamProf/MatBlazor#235] opened 2019-09-06 08:26 UTC
On Blazor Server, no standard httpclient is registered. Looks like the MatTable throws an Exception because no HttpClient present.

Error message:
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'Http' on type 'MatBlazor.MatTable`1[...]'. There is no registered service of type 'System.Net.Http.HttpClient'.
System.InvalidOperationException: Cannot provide a value for property 'Http' on type 'MatBlazor.MatTable`1[...]'. There is no registered service of type 'System.Net.Http.HttpClient'.

**Comment by whentotrade** [comment] 2019-09-06 08:31
This is my workaround by adding the following in the `ConfigureServices`. However, this scoped services is not needed, just to prevent and workaround the error mentioned above.

```
// Server Side Blazor doesn't register HttpClient by default
if (!services.Any(x => x.ServiceType == typeof(HttpClient)))
{
   // Setup HttpClient for server side in a client side compatible fashion
   services.AddScoped<HttpClient>(s =>
   {
            // Creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.
            var uriHelper = s.GetRequiredService<NavigationManager> ();
            return new HttpClient
             {
                  BaseAddress = new Uri(uriHelper.BaseUri)
             };
     });
}
```

**Comment by SeppPenner** [comment] 2019-09-06 08:31
If I remember correctly, the following code can solve this. At least, it worked with preview8 before like that.

```csharp
if (services.All(x => x.ServiceType != typeof(HttpClient)))
    {
        services.AddScoped(
            s =>
            {
                var navigationManager = s.GetRequiredService<NavigationManager>();
                return new HttpClient
                {
                    BaseAddress = new Uri(navigationManager.BaseUri)
                };
        });
    }
```

Add this to the `ConfigureServices` method under `Startup` in the server side project.

**Comment by SeppPenner** [comment] 2019-09-06 08:32
> This is my workaround by adding the following in the `ConfigureServices`. However, this scoped services is not needed, just to prevent and workaround the error mentioned above.

Haha, you were faster ;)

**Comment by whentotrade** [comment] 2019-09-06 08:33
@SeppPenner : Thank you anyhow, yes this is my workaround
!

**Comment by iAmBipinPaul** [comment] 2019-09-06 08:39
Looks like duplicate of  https://github.com/SamProf/MatBlazor/issues/196

**Comment by SeppPenner** [comment] 2019-09-06 08:54
It is a duplicate of https://github.com/SamProf/MatBlazor/issues/196.

**Comment by SamProf** [comment] 2019-09-08 14:30
Duplicate of #196

**Closed by SamProf** 2019-09-08 14:30 UTC
