### ISSUE TITLE
MatSelectValue not select at startup component

### ISSUE THREAD

**Issue by andreatosato** [SamProf/MatBlazor#498] opened 2020-04-20 06:47 UTC
Hi,
I'm trying MatBlazor for community project.
MatSelectValue not select default value at component startup.
My code:
```html
<MatSelectValue Items="@PeopleToSelect" TValue="PersonUpdateViewModel" TItem="PersonUpdateViewModel"
				ValueChanged="PersonSelectedChanged" ValueExpression="@(() => PersonSelected)" ValueSelector="@(i=>i)"
				HelperTextPersistent="false" Label="Seleziona la persona">
	<ItemTemplate>
		<img src="@ImageUrl(context.Picture)" />&nbsp;<span>@context.Name @context.Surname</span>
	</ItemTemplate>
</MatSelectValue>
```
**Effect**

1. Startup (**wrong becase there is pre-select element but not show that**)
![2020-04-20_08h43_29](https://user-images.githubusercontent.com/24985956/79721732-24836780-82e3-11ea-9093-4e6cff974005.png)
2. When select element manually
![2020-04-20_08h43_40](https://user-images.githubusercontent.com/24985956/79721752-3107c000-82e3-11ea-8ffd-58b480c2e1f7.png)
3. When select element manually (**correct, but I need to select manually**)
![2020-04-20_08h43_47](https://user-images.githubusercontent.com/24985956/79721764-37963780-82e3-11ea-8fb2-a1092094b508.png)

[Component](https://github.com/andreatosato/Community-Italy/blob/master/src/CommunityItaly/CommunityItaly.Web/Components/People/PersonSelect.razor)
[Code Behind](https://github.com/andreatosato/Community-Italy/blob/master/src/CommunityItaly/CommunityItaly.Web/Components/People/PersonSelect.razor.cs)

**Second question:**
I need to use "FullWidth" same others component.
I can't see this option, why?

**Comment by jjchiw** [comment] 2020-05-04 22:40
I think i got the same behaviour.... 


```
@page "/"
 
        <MatSelect Label="Pick a Food Group" TValue="string" @bind-Value="@sel" Outlined="true">
          @foreach (var item in items)
            {
                <MatOptionString Value="@item">@item</MatOptionString>
            }
        </MatSelect>
        @sel
    
@code {
    string sel = "grains";
    List<string> items = new List<string>();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (firstRender) 
        {
            items = new List<string> {"grains", "vegetables", "fruit"};
        }
    }
}
```

https://blazorfiddle.com/s/q52518g6


The `sel` variable after setting the new list values it goes blank...

If we initialize the list
`List<string> items = new List<string> {"grains", "vegetables", "fruit"};`
it works as expected

I tried instead of assigning a list in `OnAfterRenderAsync` do a `AddRange` `Add` but it behaves the same....

**Comment by lindespang** [comment] 2020-05-08 23:54
Hi!

Thanks for using MatBlazor.

> **Second question:**
> I need to use "FullWidth" same others component.
> I can't see this option, why?

Please create another issue regarding this so we can keep the issues atomic. :)

Im closing this as a duplicate of #494 please follow the discussion there. I believe a pending fix for MDCSelect will solve this (hopefully shortly)

**Closed by lindespang** 2020-05-08 23:54 UTC

**Comment by WinInsider** [comment] 2020-06-22 17:13
I am experiencing same issue with MatSelect… essentially, if **Items List** is populated dynamically at runtime (say from database) MatSelect does not **visual** "select" any of the items provided.

**Comment by Ogglas** [comment] 2021-03-08 21:16
I spent so many hours trying to get this to work with `MatSelectValue`. 

I ended up using a simple `MatSelect` with a property calling my `ValueChanged` method. This is the only way I got the select list to prefill correctly. 

Example with nullable int but you can change to string, guid etc as well. 

https://www.matblazor.com/Select#MatSelectGuid

```
@inject StateContainer StateContainer

<MatSelect Label="Choose threat" @bind-Value="@SelectThreatId" Outlined="true" FullWidth="true">
    @foreach (var item in selectThreats)
    {
        <MatOption TValue="int?" Value="@item.Id">@item.Threat</MatOption>
    }
</MatSelect>

@code
    {

    [Parameter]
    public ThreatAndCountermeasureDto ThreatAndCountermeasureDto { get; set; }

    List<ThreatDto> selectThreats = new List<ThreatDto>();

    ThreatDto selectedThreat = null;

    private int? threatId = null;

    public int? SelectThreatId
    {
        get { return threatId; }
        set
        {
            threatId = value;
            SelectThreatValueChanged(value);
        }
    }
	
    private void SelectThreatValueChanged(int? id)
    {
        selectedThreat = StateContainer.Threats.Single(x => x.Id == id);
    }
	
    protected override void OnInitialized()
    {
        base.OnInitialized();
        StateContainer.OnChange += StateHasChanged;
        SelectThreatId = ThreatAndCountermeasureDto.Threat.Id;
        selectThreats = StateContainer.Threats.ToList();
    }
	...


```
